version: '3'
services:
  go:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: ['go', 'run', 'app/main.go']
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
# psql -h 127.0.0.1 -p 5432 -U myuser mydb
